# Generated by Django 2.1.3 on 2018-11-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=8)),
                ('iso', models.CharField(max_length=3)),
                ('countryslug', models.CharField(max_length=3)),
                ('countryname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('timeon', models.TimeField()),
                ('timeoff', models.TimeField()),
                ('mon', models.BooleanField(blank=True)),
                ('tue', models.BooleanField(blank=True)),
                ('wed', models.BooleanField(blank=True)),
                ('thu', models.BooleanField(blank=True)),
                ('fri', models.BooleanField(blank=True)),
                ('sat', models.BooleanField(blank=True)),
                ('sun', models.BooleanField(blank=True)),
                ('power', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('uuid', models.SlugField()),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shortwave.Broadcaster')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shortwave.Language')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shortwave.Site')),
            ],
        ),
    ]
