# Generated by Django 2.1.3 on 2018-12-06 20:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('content', markdownx.models.MarkdownxField()),
                ('sortorder', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='broadcaster',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
