# Generated by Django 2.1.3 on 2018-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortwave', '0004_auto_20181209_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
            ],
        ),
    ]
