# Generated by Django 2.1.3 on 2018-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortwave', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
