# Generated by Django 2.1.3 on 2018-12-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortwave', '0006_blogpost_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='uuid',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
